### ISSUE TITLE
credentialHelper

### ISSUE THREAD

**Issue by giano574** [RaphaelJenni/FirebaseUI-Angular#20]
In the FirebaseUI for Web - Auth, there is an option to specify the credentialHelper to use (https://github.com/firebase/firebaseui-web#credential-helper) in the options. This is option is missing in your library. Is there a temporary workaround?

**Comment by RaphaelJenni** [comment]
I can fix that. Maybe this evening, but else I need a few days, as I don't know when I have time. Otherwise, you can create a PR.
Anyway, by default, it chooses the account chooser. To test it locally without the account chooser, you can hard code it directly to the library in the node_modules or deploy your one version.

**Comment by RaphaelJenni** [comment]
Fixed it. Version 0.4.5 is live. There's now a configuration option called CredentialHelper
