### ISSUE TITLE
Update README on how to run the demo app

### ISSUE THREAD

**Issue by francoisr** [RaphaelJenni/FirebaseUI-Angular#64]
Hello, thanks for the angular wrapper.
Just a comment that the readme mentions a sample directory for a demo. Such a folder does not exist.
Could you include the sample folder, would it be only for newbies like myself.

There may be other ways to have the app work but I managed to get the demo working by ng serve of the /src folder only after
1 - main.module.ts couldn't resolve the firebaseui-angular reference. 
2 - I couldn't npm install firebaseui-angular because the package name and the project name were identical.
3 - I changed the package name in /src/package.json.
4 - tsconfig.json had an invalid reference to firebaseui-angular  under path that I removed without issue.

Now that I think about it, I could have somehow build to create the missing dist folder, but there the readme does not instruct to do so to run the demo.

Bottomline, the request is for a little completeness of the readme, I may save newbies like me a couple of hours struggling :)

Regards,

**Comment by RaphaelJenni** [comment]
Hi, I have to update the README. The Demo project is now the root. The library is located inside the `projects/firebaseui-angular-library folder.

To run the demo you have to run `npm install` in the root of the app and run `ng serve` afterward.
This will show you an error because of the missing configurations. (https://github.com/RaphaelJenni/FirebaseUI-Angular/blob/master/src/environments/environment.ts#L7) Add them and you are good to go.

**Comment by RaphaelJenni** [comment]
@francoisr Sorry forgot a step. before running `ng serve`, **build the library with** `npm run build-lib`

**Comment by francoisr** [comment]
Thanks for the reply. In the end, I missed building the libraries by running the `npm run build-lib` line. i overlooked it because it is mentioned under Development, not under Sample. 
Cheers!
`
